### ISSUE TITLE
Add disclaimer on data downloads

### ISSUE THREAD

**Issue by jvanulde** [OpenDRR/opendrr-platform#74]

**Comment by plesueur** [comment]
I assume this is the documentation that will accompany the dataset release: https://jvanulde.github.io/data/en/nhsl.html#physical_exposure

I propose the following edits to the last paragraph for the physical exposure dataset:
_The building inventory is aligned with international standards for multi-hazard risk assessment. It was developed for use in national scale seismic risk assessment, but is suitable for use in other natural hazards assessments that may require specific information on land-use or buildings and their occupants. This dataset, in its current version, is not applicable to site- or building-specific assessment._ 

I propose we add the following paragraph to the social fabric and capacity thresholds section:
_This dataset is best suited to understand relative levels of social vulnerability to natural hazards within a municipality or larger region. The provided vulnerability scores are based on a range of indicators that are commonly used in North America for such analysis. However, social vulnerability is a complex phenomenon that can arise because of several interrelated factors, some of which might not be accounted for in this dataset. Any assessments that use this information at local scales will benefit from considering context specific factors that might drive social vulnerability alongside the information provided._ 

@mjourneay, @jvanulde or @tieganh, any edits/comments?

**Comment by tieganh** [comment]
Hey folks - thanks for inviting my feedback! I'm not sure I'm in a position to make any comments on the social vulnerability piece and in fact would maybe consider asking someone with a background in social science just to cover bases about best practices at this moment? Maybe [Ryan Reynolds at UBC ](https://scarp.ubc.ca/people/ryan-reynolds). Not to insinuate this group isn't well positioned to make a meaningful contribution to SoVu work, just that none of us (except Jackie, if I understand correctly) is formally trained in that field. 

Maybe it's especially important because this is [as far as I understand] being published prior to the publication of the peer-reviewed document to accompany, which is somewhat at odds with NRCan's policy on scientific integrity which promotes open access to scientific material but also requires peer review for scientific communications and research dissemination. I hadn't actually read it until this morning, to make sure I wasn't speaking out of line, but here it is in case it's of interest: [NRCan Scientific Integrity](https://www.nrcan.gc.ca/sites/www.nrcan.gc.ca/files/department/nrcan-sip-en-2018-12-20.pdf), Section 7.5.6 in particular.

For the physical exposure wording, I'd find the wording of the last couple of lines a little confusing. It "is suitable for ... assessments that may require specific information on ... buildings and their occupants", but "is not applicable to site- or building-specific assessment". Perhaps instead it would be good to use the term "representative" to help folks understand it isn't a direct inventory but rather a representative database that generally matches the land use typologies and associated built environment/occupancy at a regional level.

**Comment by jvanulde** [comment]
Excellent points @tieganh. Do we need to rethink making these data public?

**Comment by plesueur** [comment]
@tieganh, really good points. Good catch, and makes sense to me to hold off until we have completed the review process.

**Comment by jvanulde** [comment]
@plesueur @tieganh we would have to make the data repo private if a review is required prior to publishing. Just an FYI. Easy to do. Let me know.

**Comment by jvanulde** [comment]
@malaikau has consulted NRCan legal on this. Waiting on a response...

**Comment by jvanulde** [comment]
NRCan legal said that the Open Canada license will be sufficient.
